### ISSUE TITLE
Please provide 16.0-patched.json

### ISSUE THREAD

**Issue by mickroll** [ccouzens/keycloak-openapi#15]
Please do your magic and provide `16.0-patched.json` 🪄

**Comment by ccouzens** [comment]
I wish I could do magic :grinning:

I don't use Keycloak since I changed jobs. This is unfortunate for this project.

It is hard for me to patch the API definitions. I no longer use Keycloak's API so I'm not familiar with what's missing.

I've been hoping that someone else from the community will do the work of manually patching the definitions https://github.com/ccouzens/keycloak-openapi/issues/10

Sorry I can't be more helpful with the patched version

**Comment by famod** [comment]
Bummer, but understandable.

I not aware of any "history" about this, but has there ever been an official request in the Keycloak Jira?

**Comment by ccouzens** [comment]
I've been following this Jira ticket about it

https://issues.redhat.com/browse/KEYCLOAK-9655

Every week or 2 the issue would be updated to a new sprint. I think the Keycloak team want to provide their own OpenAPI definitions- but maybe it's not their highest priority.

It looks like the issue has been moved to Github https://github.com/keycloak/keycloak/issues/8759

**Comment by famod** [comment]
FTR, I started a discussion in the Quarkus Zulip chat (kinda "hijacking" another keycloak topic where KC maintainers were discussing): https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Keycloak.2016.20questions/near/267939286

**Comment by DAHAG-ArisNourbakhsh** [comment]
I didn't want to wait any longer for keycloak to generate the openApi definition and decided to just parse out the Java source code to generate a slightly more type-safe definition. 

Disclaimer: Might even be more wonky than parsing the online documentation and we do not use all the endpoints but the few we do, work. 

https://github.com/dahag-ag/keycloak-openapi

**Comment by ccouzens** [comment]
> I didn't want to wait any longer for keycloak to generate the openApi definition and decided to just parse out the Java source code to generate a slightly more type-safe definition.
> 
> Disclaimer: Might even be more wonky than parsing the online documentation and we do not use all the endpoints but the few we do, work.
> 
> https://github.com/dahag-ag/keycloak-openapi

Thank you @DAHAG-ArisNourbakhsh 

I've added a link to your project in the Readme 0d8d3c93f6438089eba88345e13d37f653f393e1

**Comment by mickroll** [comment]
Obsolete, see post above
