### ISSUE TITLE
Add tags for grouping paths

### ISSUE THREAD

**Issue by yordis** [ccouzens/keycloak-openapi#2]
Hey there,

First, thank you very much for putting this together.

It would be great to follow the documentation https://www.keycloak.org/docs-api/5.0/rest-api/index.html left section where they group the paths in a logical way using tags https://swagger.io/docs/specification/grouping-operations-with-tags/

- Attack Detection
- Authentication Management
- Client Attribute Certificate
- Client Initial Access
- Client Registration Policy
- Client Role Mappings
- Client Scopes
- Clients
- Component
- Groups
- Identity Providers
- Key
- Protocol Mappers
- Realms Admin
- Role Mapper
- Roles
- Roles (by ID)
- Scope Mappings
- User Storage Provider
- Users
- Root

**Comment by ccouzens** [comment]
Thank you for the good idea. I'll give this a go at the weekend

**Comment by ccouzens** [comment]
Done and pushed to master.

Let me know how you get on with the tags.
