### ISSUE TITLE
OpenAPI spec file for Keycloak account API

### ISSUE THREAD

**Issue by xgp** [ccouzens/keycloak-openapi#31]
I don't know if you want to include this, but I made a pass at an OpenAPI spec file for Keycloak account API:

https://gist.github.com/xgp/2d77cbebc6164160faae6aa77d127a57

Based on the code here: https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/resources/account/AccountRestService.java

This would be useful for anyone building a custom account console, or building account info/editing into their application. 

Let me know if you want to add this, and I'll put together a PR for it.

**Comment by ccouzens** [comment]
Hey xgp,

Yeah, I'd be happy to include it.

I don't mind if it goes in this repo, or if it's a link and description in my readme to your repo or GitHub gist.

Thanks,
Chris
