### ISSUE TITLE
Add Keycloak 22.0.1 -> 23.0.1

### ISSUE THREAD

**Issue by rblaine95** [ccouzens/keycloak-openapi#38]
Generate OpenAPI Docs for Keycloak 22.0.1 -> 23.0.1
* https://www.keycloak.org/2023/11/keycloak-2300-released.html
* https://www.keycloak.org/2023/11/keycloak-2301-released.html
* https://www.keycloak.org/docs-api/23.0.1/rest-api/index.html

**Comment by kallberg** [comment]
Added version 23.0.0, 23.0.1 and the missing patch versions for 22. 

Version 23 looks promising compared to version 22. They have added more types in their api docs now.

**Comment by rblaine95** [comment]
Awesome @kallberg, thank you!
