### ISSUE TITLE
Add operationId to method definition

### ISSUE THREAD

**Issue by supapo** [ccouzens/keycloak-openapi#8]
Hi, thank you for the great project
Is it possible to add the operationId parameter to each method?

If I can contribute to this feature please tell me how

**Comment by ccouzens** [comment]
Hi, @supapo 

It's great you're finding it useful.

>  Is it possible to add the operationId parameter to each method?

I don't know how I could do this in an automated way.

I don't think there's anything in the [HTML](https://www.keycloak.org/docs-api/12.0/rest-api/index.html) I could use.
The `id` tag in the HTML comes close, but unfortunately isn't unique. For example `getmapperbyid` appears 3 times (`[...document.querySelectorAll('[id=_getmapperbyid]')]`).

I'm happy to discuss suggestions of how you think it might work.

Kind regards,
Chris

**Comment by supapo** [comment]
Hi Chris, 
You right, there are more than one instances of some function, as well as meaningless names such as "update"
Those are the insteanses of the getMapperById
integration/admin-client/src/main/java/org/keycloak/admin/client/resource/IdentityProviderResource.java:76:    
IdentityProviderMapperRepresentation getMapperById(@PathParam("id") String id);
integration/admin-client/src/main/java/org/keycloak/admin/client/resource/ProtocolMappersResource.java:61:    ProtocolMapperRepresentation getMapperById(@PathParam("id") String id);
services/src/main/java/org/keycloak/services/resources/admin/IdentityProviderResource.java:383:    public IdentityProviderMapperRepresentation getMapperById(@PathParam("id") String id) {
services/src/main/java/org/keycloak/services/resources/admin/ProtocolMappersResource.java:188:    public ProtocolMapperRepresentation getMapperById(@PathParam("id") String id) {

I think that the best way is to contribute to the Keycloak source of meaningful function names
Also please look at this topic https://github.com/keycloak/keycloak/pull/5198#issuecomment-533453316

Kind regards, and thanks in advance
Menashe

**Comment by ccouzens** [comment]
Thanks Menashe,

If the upstream keycloak project adds better `id`s, I'm use them here.
But I don't have the time add them to keycloak itself.

I'll close this issue for now.

Kind regards,

Chris
